name: ci
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: poetry install
      - run: poetry run flake8 gendiff
      - name: run tests
        run: poetry run pytest --cov=gendiff tests/ --cov-report xml
